### ISSUE TITLE
Can I use this code to recognize pose like write or hands up？

### ISSUE THREAD

**Issue by wzj9812** [LexingtonWhalen/JoJoPoseEstimation#1]
hello，i try to use openpose to recognize some students' poses in class? How can i refer this code?

**Comment by LexingtonWhalen** [comment]
I would look at https://github.com/LexingtonWhalen/PoseAngleEstimation first. The code is more for recognizing limb poses, so hands may not work as well as the angles of hands may not be the same as angles of arms.
